import os
# set your AZURE_OPENAI_API_BASE, AZURE_OPENAI_API_KEY here!
API_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
os.environ["AZURE_OPENAI_API_KEY"] = API_KEY

# OPENAI_API_KEY = "XXXXXXXXXXXXXXXXXXXX"
# os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
# API_BASE = "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# os.environ["OPENAI_API_BASE"] = API_BASE

AZURE_OPENAI_ENDPOINT = "https://XXXXXXXX.openai.azure.com/"
OPENAI_API_VERSION = "2024-02-01"
os.environ["AZURE_OPENAI_ENDPOINT"] = AZURE_OPENAI_ENDPOINT
os.environ["OPENAI_API_VERSION"] = OPENAI_API_VERSION

# MODEL_NAME="gpt-4o-mini"
MODEL_NAME="gpt-4o"
# MODEL_NAME="gpt-3.5-turbo"
