# core/vision_vllm_config.py
"""
Configuration for local vision model inference via vLLM.
"""
from core.config import (
    USE_VISION_VLLM,
    ENABLE_REVIEWER_AGENT,
    VISION_VLLM_HOST,
    VISION_VLLM_PORT,
    VISION_VLLM_BASE_URL,
    VISION_VLLM_MODEL_NAME,
    VISION_VLLM_MAX_MODEL_LEN,
    VISION_VLLM_MAX_TOKENS,
    VISION_VLLM_TEMPERATURE,
    VISION_VLLM_GPU_MEMORY_UTILIZATION,
    VISION_VLLM_QUANTIZATION,
    VISION_VLLM_DTYPE
)
